### ISSUE TITLE
NAMESPACE issue

### ISSUE THREAD

**Issue by restonslacker** [vnijs/gitgadget#1]
The documented function gitgadget() is not actually exported.

**Comment by vnijs** [comment]
`gitgadget` is intended to run from the Addins menu in Rstudio. However, you can also call it using `gitgadget:::gitgadget()`. That said, I will export the `gitgadget` function, and a few others in the next update. Thanks

**Comment by restonslacker** [comment]
oh, i understand that the addins menu is the intended method of access, but the help documentation looks like you had intended to export the function.

![capture](https://cloud.githubusercontent.com/assets/5813515/18555757/01f53e9e-7b37-11e6-82a3-d19aebcd930d.PNG)

**Comment by vnijs** [comment]
Correct. Updated on github. Will push a new binary to minicran this afternoon. Thanks for reporting @restonslacker
