### ISSUE TITLE
DESCRIPTION issue

### ISSUE THREAD

**Issue by restonslacker** [vnijs/gitgadget#2]
The site url https://gitlab.com/vnijs/gitgadget does not exist (gitlab versus github).

**Comment by vnijs** [comment]
Thanks for reporting @restonslacker. The link is fixed on github and I created a copy of the repo on gitlab. To get the latest (binary) version of gitgadget you can use the command below. 

``` r
install.packages(“gitgadget”, repos = “https://radiant-rstats.github.io/minicran/”, type = “binary”)
```

**Comment by restonslacker** [comment]
thanks for this and Radiant!
